# Generated by Django 5.2.14 on 2026-05-08 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="joined_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
