# Generated by Django 5.2.14 on 2026-05-10 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_student_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="students.course",
            ),
        ),
    ]
